# The dictionaries defined below should be named based on the controller prefix as defined in the configuration

RSC_sensor_names = {
  b'1': "PcbVolt",
  b'2': "PcbCurrent",
  b'3': "PcbTemperature",
  b'101': "Supply Pressure",
  b'102': "Return Pressure",
  b'103': "High Temperature",
  b'104': "Low Temperature",
  b'105': "Controller Voltage",
  b'106': "Controller Current",
  b'107': "Controller Temperature",
}

SPFC_sensor_names = {
  b'1': "spfcVoltage",
  b'2': "spfcCurrent",
  b'3': "spfcTemp",
}

SPFC_helium_sensor_names = {
  b'1': "heControllerVoltage",
  b'2': "heControllerCurrent",
  b'3': "heControllerTemp",
  b'4': "heCompSupplyPressure",
  b'5': "heCompReturnPressure",
  b'6': "heCompMotorTemp",
  b'7': "heCompSupplyTemp",
}

RSC_receiver_sensor_names = {
  b'1': "RCME Voltage",
  b'2': "RCME Current",
  b'3': "RCME Temperature",
  b'4': "LNA-H Drain_Volt",
  b'5': "LNA-H Gate_Volt",
  b'6': "LNA-H Drain_Current",
  b'7': "LNA-V Drain_Volt",
  b'8': "LNA-V Gate_Volt",
  b'9': "LNA-V Drain_Current",
  b'10': "2nd Stage Amp H-Current",
  b'11': "2nd Stage Amp V-Current",
  b'12': "Cal Source Current",
  b'13': "Cal Source Voltage",
  b'14': "RFE 1st Stage Heater Current",
  b'15': "RFE 2nd Stage Heater Current",
  b'16': "Cryostat Pressure",
  b'17': "Manifold Pressure",
  b'18': "RFE 1st Stage Temperature",
  b'19': "RFE 2nd Stage Temperature",
  b'20': "OMT Temperature",
  b'21': "Cryo 1st Stage Temperature",
  b'22': "Cryo Body Temperature",

# I/O values
  b'101': "LNA-H Power",
  b'102': "LNA Illumination",
  b'103': "Amp2-V Power",
  b'104': "Temp Control2",
  b'105': "Spare I/O's",
  b'106': "LNA-V Power",
  b'107': "Amp2-H Power",

# Control values
  b'201': "RFE1 Temp select",
  b'202': "Stepper Frequency",
  b'203': "Valve Status",
}

SPFC_receiver_spf1_sensor_names = {
  b'1': "b1ControllerVoltage",
  b'2': "b1ControllerCurrent",
  b'3': "b1ControllerTemp",
  b'4': "b1PsuRectifiedVoltage",
  b'5': "b1PsuAnalogue6VRegulatorTemp",
  b'6': "b1PsuAnalogue15VRegulatorTemp",
  b'7': "b1PsuDigital6VRegulatorTemp",
  b'8': "b1LnaHDrainVoltage",
  b'9': "b1LnaHDrainCurrent",
  b'10': "b1LnaHGateVoltage",
  b'11': "b1LnaVDrainVoltage",
  b'12': "b1LnaVDrainCurrent",
  b'13': "b1LnaVGateVoltage",
  b'14': "b1Amp2HVoltage",
  b'15': "b1Amp2HCurrent",
  b'16': "b1Amp2VVoltage",
  b'17': "b1Amp2VCurrent",
  b'18': "b1CalSourceVoltage",
  b'19': "b1CalSourceCurrent",
  b'20': "b1CalSourceTemp",
  b'21': "b1CalSourcePidCurrent",
  b'22': "b1LnaHPidCurrent",
  b'23': "b1LnaVPidCurrent",
  b'24': "b1BodyTemp",
  b'25': "b1AnalogueInterfaceTemp",
  b'26': "b1LnaHTemp",
  b'27': "b1LnaVTemp",
  b'28': "b1SpdHealth",
  
# I/O values
  b'101': "b1LnaHPowerState",
  b'102': "b1LnaVPowerState",
  b'103': "b1Amp2HPowerState",
  b'104': "b1Amp2VPowerState",
  b'105': "b1Spare1",
  b'106': "b1Spare2",
  b'107': "b1CalSourcePowerState",
  b'108': "b1CalSourcePidPowerState",
  b'109': "b1LnaHPidPowerState",
  b'110': "b1LnaVPidPowerState",

# Control values
  b'201': "b1CalSourcePidTempSetPoint",
  b'202': "b1LnaHPidTempSetPoint",
  b'203': "b1LnaVPidTempSetPoint",
}


SPFC_receiver_spf2_sensor_names = {
  b'1':	"b2ControllerVoltage",
  b'2':	"b2ControllerCurrent",
  b'3':	"b2ControllerTemp",
  b'4':	"b2Psu9VRectifiedVoltage",
  b'5':	"b2PsuDigital6VRegulatorTemp",
  b'6': "b2PsuAnalogue15VRegulatorTemp", 
  b'7': "b2PsuAnalogue6VRegulatorTemp", 
  b'8': "b2LnaHDrainVoltage1", 
  b'9': "b2LnaHDrainVoltage2", 
  b'10': "b2LnaHDrainVoltage3",
  b'11': "b2LnaHDrainCurrent1",
  b'12': "b2LnaHDrainCurrent2",
  b'13': "b2LnaHDrainCurrent3",
  b'14': "b2LnaHGateVoltage1",
  b'15': "b2LnaHGateVoltage2",
  b'16': "b2LnaHGateVoltage3",
  b'17': "b2LnaVDrainVoltage1",
  b'18': "b2LnaVDrainVoltage2",
  b'19': "b2LnaVDrainVoltage3",
  b'20': "b2LnaVDrainCurrent1",
  b'21': "b2LnaVDrainCurrent2",
  b'22': "b2LnaVDrainCurrent3",
  b'23': "b2LnaVGateVoltage1",
  b'24': "b2LnaVGateVoltage2",
  b'25': "b2LnaVGateVoltage3",
  b'26': "b2Amp2HVoltage",
  b'27': "b2Amp2HCurrent",
  b'28': "b2Amp2VVoltage",
  b'29': "b2Amp2VCurrent",
  b'30': "b2CalSourceVoltage",
  b'31': "b2CalSourceCurrent",
  b'32': "b2CalSourceTemp",
  b'33': "b2CalSourcePidCurrent",
  b'34': "b2LnaPidCurrent",
  b'35': "b2CryostatPressure",
  b'36': "b2ManifoldPressure",
  b'37': "b2LnaTemp",
  b'38': "b2OmtTemp",
  b'39': "b2ColdheadStage1Temp",
  b'40': "b2BodyTemp",
  b'41': "b2AnalogueInterfaceTemp",
  b'42': "b2PsuMotorPosSupplyCurrent",
  b'43': "b2PsuMotorNegSupplyCurrent",
  b'44': "b2PsuMotorDriverTemp",
  b'45': "b2SpdHealth",
  
# I/O values
  b'101': "b2LnaHPowerState",
  b'102': "b2LnaVPowerState",
  b'103': "b2Amp2HPowerState",
  b'104': "b2Amp2HPowerState",
  b'105': "b2LnaHIlluminationState",
  b'106': "b2LnaVIlluminationState",
  b'107': "b2CalSourcePowerState",
  b'108': "b2CalSourcePidPowerState",
  b'109': "b2LnaPidPowerState",

# Control values
  b'201': "b2LnaPidTempSetPoint",
  b'202': "b2CalSourcePidTempSetPoint",
  b'203': "b2VaValveState",
  b'204': "b2CryoMotorSpeed",
}

# The above numbers corresponds data seperated by collumns. This describes the data in the attached .log file.
# Plot the exact same data as the code in my previous message but adapt it to the new data.